### PR TITLE
Support word-size values and memory management

### PR DESCRIPTION
**Pull request by j-hui**
This is a work-in-progress proposal for changes to the ssm-runtime API to support our schema of uniformly word-size values. This comes with several advantages:
- Word-size values enables relatively straightforward automatic memory management a la OCaml (though in our case we use a reference counted scheme rather than a garbage collector)
- Having a uniform value size means that we can also have a uniform scheduled variable representation, and eliminate the need for a `update` function pointer
- Having a truly polymorphic `update` function means that we can support external updates which bypass the input queue entirely, an optimization that an I/O driver (specifically the input driver) can take advantage of

For now, this is just a draft of what this runtime could look like. @Scanteianu will help integrate his implementation of the memory management mechanism here, and hopefully eventually we will be able to do away with the use of `malloc` in this library altogether.

### CODE REVIEW

**Comment by j-hui** [comment]
@sedwards-lab I updated a couple of examples to use the new memory model and API; clock and fib3 seem to be working so far. I also updated the pseudocode in the comments to use sslang syntax. Should we just deprecate some of the old examples? Some of them use non-standard calling conventions, like passing variables via static linkage, etc. While it might be interesting for some compiler to generate code that does that, I'm not sure if it's illustrative as an example for this repo.

Note that I added `ssm-types.h` to supplement `ssm.h` with a bunch of typedefs for the old typenames. This is just name mangling, and won't be needed by compiler-generated code---we don't actually need any of the type-specific methods anymore since we're now using a uniform value representation. I just use the old `ssm_i32_t` and `ssm_event_t` type names purely for readability.

**Comment by j-hui** [comment]
~I'm also planning on factoring out `SSM_MALLOC` out of `ssm_enter`, so that allocation of activation records can be handled outside of the runtime. All `ssm_enter` needs to do is initialize fields appropriately (and same with `ssm_leave`).~

Turns out this is quite unnecessary. I'm reverting to the old ssm_enter semantics to hide the internal use of the allocator.

**Comment by Rewbert** [comment]
Looks cool, and it seems nice to have a uniform representation of data, especially when moving events from the IO queue to the SSM queue. I am going to add ADTs very soon so having a clear picture of what my generated code will look like is great.

What is the current status of this? Are there any question marks to iron out before the switch can be made? Is there anything that I can help with? I am guessing there will be room for me to learn new things from this refactoring :)

**Comment by j-hui** [comment]
@Rewbert I'm currently doing a reorganization of things so that (1) it's clearer what the external (user code-facing) and internal (platform code-facing) interfaces are, and (2) it's easier to integrate other subsystems for memory management and platform-specific I/O code (see #4 ).

I still need to patch up a bunch of the examples and test code, and just get everything building again, plus I need to stub out some basic interface for reference counting memory management.

**Comment by j-hui** [comment]
Wow this code coverage thing is fancy. Let's see if it actually produces insightful remarks wrt telling us about changes in code coverage between diffs.

**Review by sedwards-lab — APPROVED** [review]
54 files changed? I didn't know we even had 54 files. In any case, I trust you on this.

**Comment by j-hui** [comment]
Yeah I was surprised too until I remembered that we used to have a different file for each builtin type (e.g., `ssm-bool.c`, `ssm-i32.c`, etc.). And then there also used to be more test cases than are currently present.

**Pull request merged**
