### PR TITLE
Support uniform memory model, memory management, and ADTs

### PR DESCRIPTION
**Pull request by j-hui**
This PR will rebase multiple commits accumulated on the `dev` branch into `main`. It revamps the memory model, representation, and management of SSM programs, and adds support for ADTs. It also revamps introduces some CI actions to automatically run tests, and automatically build and deploy code documentation.

I had previously held back on landing this to `main` because I wanted to make sure it was stable before we committed to porting existing dependents to this updated runtime. Now that this is well under way on both fronts---Scoria, led by @Rewbert, and sslang, joint work between myself and @EmilySillars---we should also move forwards with "releasing" this next version of the runtime.

Features that did not make it into this release, and this time of writing:

- [ ] Support for closures (#25)
- [ ] Support for arrays
- [ ] Direct PlatformIO support (#4)
- [x] macOS CI (#17)

I hope to land this PR this in by the end of this week (Feb 4); earlier if possible, though I will wait for the above PRs to be completed if feasible. In the meantime, I will tag the current HEAD of `main` as v0.1 so that we have a convenient pointer back to it.

### CODE REVIEW

**Comment by Rewbert** [comment]
Does github have some functionality to mark or tag main in its current state before the merge? :) If our paper is accepted and I have time to do the artifact evaluation I might need to refer to the previous version of the RTS.

**Comment by j-hui** [comment]
For sure, I've tagged the current HEAD as `cc2022` https://github.com/ssm-lang/ssm-runtime/releases/tag/cc2022 (also tagged as v0.1; I intend to tag a8e8e7e as v0.2)

**Comment by Rewbert** [comment]
Great!

**Review by sedwards-lab — APPROVED** [review]
LGTM

**Pull request merged**
